import Head from 'next/head'
import Image from 'next/image'
import { Plus_Jakarta_Sans } from 'next/font/google'
import Navbar from '@/components/Navbar/Navbar'
import Link from 'next/link';
import Spline from '@splinetool/react-spline';

import TextsmsIcon from '@mui/icons-material/Textsms';
import PlayCircleIcon from '@mui/icons-material/PlayCircle';
import KeyboardDoubleArrowDownIcon from '@mui/icons-material/KeyboardDoubleArrowDown';
import Layout from '@/components/Layout';
import FeaturedBlog from '@/components/FeaturedBlog';

const plusJakartaSans = Plus_Jakarta_Sans({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
          <div className={`font-jakartaSans flex h-[87vh] pt-12 relative flex-wrap font-medium`}>
            <div className="max-w-[500px] flex flex-col gap-6 relative z-20">
              <div className="flex gap-2 text-text-pink items-center">
                <span className="bg-text-pink h-2 w-2 rounded-full block"></span>
                <p className="text-sm">{"< Hello World! />"}</p>
                <div className='animate-waving-hand text-xl'>👋</div>
              </div>
              <div className="sm:text-4xl text-[1.75rem] leading-9 font-bold text-text-primary flex flex-col gap-2">
                <h1>I'm Raj Alam, a</h1>
                <h1 className="text-text-blue">Fullstack Web Developer</h1> 
                <h1>based on Indonesia.</h1>
              </div>
              <div>
                <p className='sm:text-base'>Welcome to my portfolio website! where i put my work, my projects, and many more.</p>
              </div>
              <div className='flex gap-4'>
                <Link href="/contact" className='flex self-start text-sm gap-2 items-center px-4 py-3 rounded bg-text-blue hover:opacity-80 text-[#222] outline-2 active:outline outline-text-blue outline-offset-2'>
                  <div>Send&nbsp;&nbsp;Message</div>
                </Link>
                <Link href="/playground" className='group px-4 text-sm b rounded text-text-pink flex'>
                  <div className="group-hover:-translate-y-1 flex gap-2 items-center transition-all group-hover:scale-110">
                    <PlayCircleIcon fontSize='large' />
                    <div className='underline'>Play Games</div>
                  </div>
                </Link>
              </div>
              <Link href="/contact" className="flex items-center gap-2 text-sm w-max hover:text-text-primary">
                <span className="bg-green-400 h-2 w-2 rounded-full h block"></span>
                <span className="underline">Have any questions?</span>
              </Link>
            </div>
            <div className='w-full h-full hidden md:block relative flex-1 -z-10 md:z-10 cursor-grab active:cursor-grabbing'>
                <Spline scene="https://prod.spline.design/lz89iZ289zK7zc8q/scene.splinecode" className='lg:scale-[.60] md:scale-50 absolute md:-top-52 md:right-80 lg:-top-52 lg:right-72' />
            </div>
            <div className='w-full absolute bottom-10 flex z-20 justify-center text-text-primary'>
              <a href="#intro">
                <KeyboardDoubleArrowDownIcon className='text-5xl animate-bounce-arrow hover:text-text-blue' />
              </a>
            </div>
          </div>
          <article className='h-screen pt-24' id='intro'>
            <FeaturedBlog />
          </article>
    </Layout>
    </>
  )
}

