import Head from 'next/head'
import { Plus_Jakarta_Sans } from 'next/font/google'
import Link from 'next/link';
import Spline from '@splinetool/react-spline';

import PlayCircleIcon from '@mui/icons-material/PlayCircle';
import KeyboardDoubleArrowDownIcon from '@mui/icons-material/KeyboardDoubleArrowDown';
import Layout from '@/components/Layout';
import FeaturedBlog from '@/components/Blog/FeaturedBlog';
import Blogs from '@/components/Blog/Blogs';
import { useState } from 'react';
import ProjectCard from '@/components/Project/ProjectCard';

const jakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"]
});

export default function Home() {
  const [loadingSpline, setLoadingSpline] = useState(true);

  const topFeaturedBlog = 
    {
      id: 1,
      title:"Curhat tentang sistem pendidikan yang ada di indonesia",
      read: 6,
      views: 334,
      date: "January 20, 3400",
      headline: "disini gwe akan membahas seluk beluk pendidikan yang ada di indonesia, ini akan menjadi pembahasan yang cukup menarik",
      categories: ["curhat", "pendidikan"],
      slug: "curhat-tentang",
    }
  

  const featuredBlogs = [
    {
        id: 2,
        image: "https://images.unsplash.com/photo-1676495090310-f1ba77badd1e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTY3ODAxOTQ3OQ&ixlib=rb-4.0.3&q=80&w=1080",
        title: "lorem ipsum dolor kamu jamet",
        read: 24,
        views: 2424,
        date: "February 18, 2023",
        headline: "what is lorem ipsum dolor asu kabeh?",
        categories: ["random", "meme", "awikawok"],
        slug: "lorem-dolor"
    },
    {
        id: 3,
        image: "https://images.unsplash.com/photo-1676044951622-85085eb5eeee?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTY3ODAxOTQ5Mw&ixlib=rb-4.0.3&q=80&w=1080",
        title: "lorem ipsum dolor kamu jamet",
        read: 24,
        views: 2424,
        date: "February 18, 2023",
        headline: "what is lorem ipsum dolor asu kabeh?",
        categories: ["random", "meme", "awikawok"],
        slug: "lorem-dolor"
    },
    {
      id: 4,
      image: "https://images.unsplash.com/photo-1677108353411-62aed3a13c77?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTY3ODAxOTUyNw&ixlib=rb-4.0.3&q=80&w=1080",
      title: "lorem ipsum dolor kamu jamet",
      read: 24,
      views: 2424,
      date: "February 18, 2023",
      headline: "what is lorem ipsum dolor asu kabeh?",
      categories: ["random", "meme", "awikawok"],
      slug: "lorem-dolor"
  },
   ] 

   const featuredProject = [
    {
        id: 2,
        image: "https://images.unsplash.com/photo-1676495090310-f1ba77badd1e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTY3ODAxOTQ3OQ&ixlib=rb-4.0.3&q=80&w=1080",
        title: "lorem ipsum dolor kamu jamet",
        read: 24,
        views: 2424,
        date: "February 18, 2023",
        headline: "what is lorem ipsum dolor asu kabeh?",
        languanges: ["random", "meme", "awikawok"],
        slug: "lorem-dolor"
    },
    {
        id: 3,
        image: "https://images.unsplash.com/photo-1676044951622-85085eb5eeee?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTY3ODAxOTQ5Mw&ixlib=rb-4.0.3&q=80&w=1080",
        title: "lorem ipsum dolor kamu jamet",
        read: 24,
        views: 2424,
        date: "February 18, 2023",
        headline: "what is lorem ipsum dolor asu kabeh?",
        languanges: ["random", "meme", "awikawok"],
        slug: "lorem-dolor"
    },
    {
      id: 4,
      image: "https://images.unsplash.com/photo-1677108353411-62aed3a13c77?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTY3ODAxOTUyNw&ixlib=rb-4.0.3&q=80&w=1080",
      title: "lorem ipsum dolor kamu jamet",
      read: 24,
      views: 2424,
      date: "February 18, 2023",
      headline: "what is lorem ipsum dolor asu kabeh?",
      languanges: ["random", "meme", "awikawok"],
      slug: "lorem-dolor"
  },
   ] 
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
          <div className={`${jakartaSans.className} flex h-[87vh] relative flex-wrap font-medium`}>
            <div className="max-w-[500px] flex flex-col gap-6 relative z-20">
              <div className="flex gap-2 text-text-pink items-center">
                <span className="bg-text-pink h-2 w-2 rounded-full block"></span>
                <p className="text-sm">{"< Hello World! />"}</p>
                <div className='animate-waving-hand text-xl'>👋</div>
              </div>
              <div className="sm:text-4xl text-[1.75rem] leading-9 font-bold text-text-primary flex flex-col gap-2">
                <h1>I'm Raj Alam, a</h1>
                <h1 className="text-text-blue">Fullstack Web Developer</h1> 
                <h1>based on Indonesia.</h1>
              </div>
              <div>
                <p className='sm:text-base'>Welcome to my portfolio website! where i put my work, my projects, and many more.</p>
              </div>
              <div className='flex gap-4'>
                <Link href="/contact" className='flex self-start text-sm gap-2 items-center px-4 py-3 rounded bg-text-blue hover:opacity-80 text-[#222] outline-2 active:outline outline-text-blue outline-offset-2'>
                  <div>Send&nbsp;&nbsp;Message</div>
                </Link>
                <Link href="/playground" className='group px-4 text-sm b rounded text-text-pink flex'>
                  <div className="group-hover:-translate-y-1 flex gap-2 items-center transition-all group-hover:scale-110">
                    <PlayCircleIcon fontSize='large' />
                    <div className='underline'>Play Games</div>
                  </div>
                </Link>
              </div>
              <Link href="/contact" className="flex items-center gap-2 text-sm w-max hover:text-text-primary">
                <span className="bg-green-400 h-2 w-2 rounded-full h block"></span>
                <span className="underline">Have any questions?</span>
              </Link>
            </div>
            <div className='w-full h-full hidden md:block relative flex-1 -z-10 md:z-10 cursor-grab active:cursor-grabbing'>
                {loadingSpline && <div className='absolute md:left-32 lg:left-52 top-32 animate-pulse'>Rendered spline...</div>}
                <Spline onLoad={() => {
                  setTimeout(() => {
                    setLoadingSpline(false)
                    }, 100)
                  }} 
                  scene="https://prod.spline.design/lz89iZ289zK7zc8q/scene.splinecode" 
                  className='lg:scale-[.60] md:scale-50 absolute md:right-80 -top-80 lg:right-72' 
                />
            </div>
            <div className='w-full absolute bottom-10 flex z-20 justify-center text-text-primary'>
              <a href="#intro">
                <KeyboardDoubleArrowDownIcon className='text-5xl animate-bounce-arrow hover:text-text-blue' />
              </a>
            </div>
          </div>
          <article className='pt-24' id='intro'>
            <FeaturedBlog topFeaturedBlog={topFeaturedBlog} />
            <Blogs blogs={featuredBlogs} />
            <Link className="hover:scale-105 duration-100 transition-all inline-block px-4 py-2 border border-[#4B5563] text-text-primary rounded mt-4" href="/blog">See More Blog</Link>
          </article>
          <section className='pt-24'>
            <h2 className="text-xl mb-8 w-max font-bold text-text-primary border-b pb-1 border-dashed border-text-pink">Featured Projects</h2>
            <article className='grid gap-4 md:grid-cols-2 lg:grid-cols-3'>
              {featuredProject.map(project => {
                return (
                  <ProjectCard projectItem={project} />
                )
              })}
            </article>
          </section>
    </Layout>
    </>
  )
}

